sudo: required
services:
  - docker

before_install:
  - docker build -t pankajsherchan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pankajsherchan/react-test npm test -- --coverage
#comment
after_success:
  - docker build -t pankajsherchan/multi-client ./client
  - docker build -t pankajsherchan/multi-server ./server
  - docker build -t pankajsherchan/multi-nginx ./nginx
  - docker build -t pankajsherchan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pankajsherchan/multi-client
  - docker push pankajsherchan/multi-server
  - docker push pankajsherchan/multi-nginx
  - docker push pankajsherchan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-122917187984
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
