sudo:required
services:
  - docker

before_install:
  - docker build -t pankajsherchan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pankajsherchan/react-test npm test -- --coverage

after_success:
  - docker build -t pankajsherchan/multi-client ./client
  - docker build -t pankajsherchan/multi-server ./server
  - docker build -t pankajsherchan/multi-nginx ./nginx
  - docker build -t pankajsherchan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pankajsherchan/multi-client
  - docker push pankajsherchan/multi-server
  - docker push pankajsherchan/multi-nginx
  - docker push pankajsherchan/multi-worker

